---
title: "Baseball-R-Dataset"
author: "Nicholas Esposito and Amber Potter"
date: "7/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Dataset

```{r}
library(baseballr)
library(tidyverse)

statcast_data_all <- read_rds("data/statcast_data_clean.rds")
```

## View proportion of NA values for each game_type
```{r}
# Infield shifting data
statcast_data_all %>%
  group_by(game_type) %>%
  count(na_if = if_fielding_alignment == "") %>%
  summarize(na_if, prop_na_if_shift = n/sum(n)) %>%
  filter(is.na(na_if)) %>%
  select(-na_if)

# Outfield shifting data
statcast_data_all %>%
  group_by(game_type) %>%
  count(na_of = of_fielding_alignment == "") %>%
  summarize(na_of, prop_na_of_shift = n/sum(n)) %>%
  filter(is.na(na_of)) %>%
  select(-na_of)
```

## TEMP: Filter for 2022; filter out ST and E games and rows in shift columns with NA values

```{r}
statcast_data_2022 <- statcast_data_all %>%
  filter(game_year == "2022", !game_type %in% c("S","E"),
         if_fielding_alignment != "" | of_fielding_alignment != "")
```


## EDA

```{r}
# Counts and percentages of variables by shift type and pitcher/batter matchups
statcast_data_2022 %>%
  #filter(!if_fielding_alignment == "", !of_fielding_alignment == "") %>%
  #select(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  count(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  mutate(prop = n/sum(n))

# Counts and percentages of variables by combination of shift type and pitcher/batter matchups
statcast_data_2022 %>%
  #filter(!if_fielding_alignment == "", !of_fielding_alignment == "") %>%
  mutate(if_fielding_alignment = case_when(if_fielding_alignment == "Infield shift" ~ "Shift",
                                           if_fielding_alignment == "Strategic" ~ "Shift",
                                           if_fielding_alignment == "Standard" ~ "Standard")) %>%
  mutate(of_fielding_alignment = case_when(of_fielding_alignment == "4th outfielder" ~ "Shift",
                                           of_fielding_alignment == "Strategic" ~ "Shift",
                                           of_fielding_alignment == "Standard" ~ "Standard")) %>%
  #select(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  count(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  mutate(prop = n/sum(n))

# Table by pitcher/batter matchups (regardless of shift type)
statcast_data_2022 %>%
  #select(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  count(stand, p_throws) %>%
  mutate(prop = n/sum(n))

# Prelim. spray charts
# statcast_data_2020_to_22 %>%
#   filter(game_year == 2022) %>%
#   ggspraychart("hc_x", "-hc_y", bin_size = 100, point_alpha = 0.25, frame = TRUE) +
#   facet_wrap(~stand)

# Group by player
statcast_data_2022 %>%
  group_by(player_name, stand) %>%
  mutate(count = n()) %>%
  filter(count > 480) %>% # ~ 480 at-bats
  count()
```

## Player Summary Stats

```{r}
statcast_data_2022 %>%
  group_by(player_name) %>%
  filter(!events == "") %>%
  mutate(walk = case_when(events == "walk" ~ 1,
                          TRUE ~ 0),
         strikeout = case_when(events == "strikeout" ~ 1,
                               TRUE ~ 0)) %>%
  summarize(stand, p_throws, if_fielding_alignment, of_fielding_alignment,
            bb_rate = mean(walk),
            k_rate = mean(strikeout),
            babip = mean(babip_value),
            woba = mean(woba_value)) %>%
  select(-player_name) %>%
  group_by(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  summarize(bb_rate = mean(bb_rate), 
            k_rate = mean(k_rate), 
            babip = mean(babip), 
            woba = mean(woba)) %>%
  ungroup() %>%
  unique()

```

## Check infield-in scenarios: runner on 3rd with less than 2 outs

```{r}
# View proportion of shifts involving above scenario
statcast_data_2022 %>%
  mutate(runner_on_third = case_when(!is.na(on_3b) & (outs_when_up < 2) ~ TRUE,
                                      TRUE ~ FALSE)) %>%
  group_by(if_fielding_alignment, of_fielding_alignment) %>%
  summarize(prop = mean(runner_on_third)) 

# Group by shift type WITHOUT filtering out infield-in
statcast_data_2022 %>%
  mutate(runner_on_third = case_when(on_3b == NA & outs_when_up == 2 ~ FALSE,
                                      TRUE ~ TRUE)) %>%
  group_by(player_name) %>%
  filter(!events == "") %>%
  mutate(walk = case_when(events == "walk" ~ 1,
                          TRUE ~ 0),
         strikeout = case_when(events == "strikeout" ~ 1,
                               TRUE ~ 0)) %>%
  summarize(stand, p_throws, if_fielding_alignment, of_fielding_alignment, runner_on_third,
          bb_rate = mean(walk),
          k_rate = mean(strikeout),
          babip = mean(babip_value),
          woba = mean(woba_value)) %>%
  select(-player_name) %>%
  filter(runner_on_third == TRUE) %>%
  group_by(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  summarize(bb_rate = mean(bb_rate), 
            k_rate = mean(k_rate), 
            babip = mean(babip), 
            woba = mean(woba)) %>%
  ungroup() %>%
  unique()

# Group by shift type WITH filtering out infield-in
statcast_data_2022 %>%
  mutate(runner_on_third = case_when(on_3b == NA & outs_when_up == 2 ~ FALSE,
                                      TRUE ~ TRUE)) %>%
  group_by(player_name) %>%
  filter(!events == "") %>%
  mutate(walk = case_when(events == "walk" ~ 1,
                          TRUE ~ 0),
         strikeout = case_when(events == "strikeout" ~ 1,
                               TRUE ~ 0)) %>%
  summarize(stand, p_throws, if_fielding_alignment, of_fielding_alignment, runner_on_third,
          bb_rate = mean(walk),
          k_rate = mean(strikeout),
          babip = mean(babip_value),
          woba = mean(woba_value)) %>%
  select(-player_name) %>%
  filter(runner_on_third == FALSE) %>%
  group_by(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  summarize(bb_rate = mean(bb_rate), 
            k_rate = mean(k_rate), 
            babip = mean(babip), 
            woba = mean(woba)) %>%
  ungroup() %>%
  unique()
```