---
title: "Modifying Dataset"
author: "Amber Potter and Nicholas Esposito"
date: "9/25/2022"
output: html_document
---

# PURPOSE: Here we we perform all modifications to the dataset (ex: mutating a new column)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in data

```{r}
V2_statcast_data <- read_rds("V2_data/V2_statcast_data_clean.rds")
```

## Data Cleaning

### Remove N/As, consolidate strikeout column, add game_id column

- Pitch outcome column will either say strikeout swinging or strikeout called.

```{r}
# Data cleaning -----------------------------------------------------------

# Clean the batting data - Remove N/As and fix strikeout cols
statcast_data_combined <- statcast_data_combined[ , colSums(is.na(statcast_data_combined)) < nrow(statcast_data_combined)]

statcast_data_combined <- statcast_data_combined %>%
  mutate(pitch_outcome = case_when(events != "" ~ events,
                                   events == "" ~ description)) %>%
  mutate(pitch_outcome = case_when(events == "strikeout" & description == "swinging_strike" ~ "strikeout_swinging",
                                   events == "strikeout" & description == "called_strike" ~ "strikeout_called",
                                   TRUE ~ pitch_outcome),
         game_id = game_pk) %>%
  select(-game_pk)

# Create at-bat counter and merge with original dataframe -----------------

# Add at-bat column for batting data (1, 2, 3...)
statcast_data_combined_at_bats <- statcast_data_combined %>%
  count(game_id, batter, at_bat_number) %>%
  group_by(game_id, batter) %>%
  mutate(at_bat_of_game=1:n()) 

# Merge to original dataframe
statcast_data_combined <- statcast_data_combined %>%
  left_join(statcast_data_combined_at_bats, 
            by = c("game_id" = "game_id", "batter" = "batter", "at_bat_number" = "at_bat_number")) %>%
  select(-n)
```

