---
title: "seasonal_model"
author: "Amber Potter"
date: "7/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load libraries and data
```{r}
library(baseballr)
library(glue)
library(tidyverse)
library(knitr)
library(ranger)
```


## Read data

```{r}
statcast_model_data <- read_rds("data/statcast_at_bat_model_data.rds")
```

## Season level variables

```{r}
seasonal_data <- statcast_model_data %>%
  group_by(batter, game_year, stand, p_throws) %>%
  summarize(avg_hit_distance = mean(hit_distance_sc, na.rm = TRUE),
            avg_launch_angle = mean(launch_angle, na.rm = TRUE),
            avg_launch_speed = mean(launch_speed, na.rm = TRUE),
            prop_shift = mean(if_fielding_alignment == "Shift"),
            prop_outside_pitches = mean(zone_simp == "Outside"),
            prop_inside_pitches = mean(zone_simp == "Inside"),
            bb_rate = mean(bb_rate),
            k_rate = mean(k_rate),
            delta_woba = mean(delta_woba),
            prop_breaking_ball = mean(general_pitch_type == "Breaking Ball"),
            .groups = "drop") %>%
  select(- batter)
```

## Seasonal model


```{r}
seasonal_data %>%
  ggplot(aes(x = delta_woba)) +
  geom_histogram()
```


```{r}
seasonal_lm <- lm(delta_woba ~ . + prop_outside_pitches * stand + prop_shift * stand - delta_woba + prop_inside_pitches * stand, data = seasonal_data)

summary(seasonal_lm)


library(ggfortify)
autoplot(seasonal_lm)
```

### 

## Plot

```{r}
seasonal_data %>%
  #ungroup() %>%
  drop_na() %>%
  mutate(pred_delta_woba = seasonal_lm$fitted.values) %>%
         #,
         #bin_pred_prob = round(pred_prob / 0.01) * .01) %>%
  # Group by bin_pred_prob:
  #group_by(bin_pred_prob) %>%
  # Calculate the calibration results:
 # summarize(#n_attempts = n(),
  #          bin_actual_prob = mean(on_base_binary)) %>%
  ggplot(aes(x = pred_delta_woba, y = delta_woba)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE) +
  geom_abline(slope = 1, intercept = 0, 
              color = "black", linetype = "dashed") +
  #facet_wrap(~ if_fielding_alignment) +
  coord_equal() + 
  scale_x_continuous(limits = c(-.1,.1)) + 
  scale_y_continuous(limits = c(-.1,.1)) + 
  labs(size = "Number of At-Bats",
       x = "Estimated Probability of Getting On Base",
       y = "Observed Probability of Getting On Base") + 
  theme_bw() +
  theme(legend.position = "bottom")
```

