---
title: "final_meeting"
author: "Nicholas Esposito and Amber Potter"
date: "7/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load `baseballr` & Other Packages

```{r}
library(baseballr)
library(glue)
library(tidyverse)
library(knitr)
```

## Read in data

```{r}
statcast_at_bat_model_data <- read_rds("data/statcast_at_bat_model_data.rds")
```

## wOBA over time by shift type

```{r}
statcast_at_bat_model_data %>%
  mutate(game_year = as.numeric(game_year)) %>%
  mutate(game_year = case_when(game_year == 1 ~ 2015,
                               game_year == 2 ~ 2016,
                               game_year == 3 ~ 2017,
                               game_year == 4 ~ 2018,
                               game_year == 5 ~ 2019,
                               game_year == 6 ~ 2021)) %>%
  group_by(game_year, stand, if_fielding_alignment) %>%
  summarize(avg_woba = mean(woba, na.rm = TRUE),
            .groups = "drop") %>%
  ggplot(aes(x = game_year, y = avg_woba, color = if_fielding_alignment)) +
  geom_line() +
  labs(x = "Year", y = "wOBA") +
  #scale_x_break(2020) +
  scale_x_continuous(breaks = seq(2015, 2021, 1)) +
  scale_y_continuous(breaks = seq(0.325, 0.400, 0.01)) +
  facet_wrap(~stand)
```
## Table with counts of number of shifted ABs for righties and lefties

```{r}
shift_count_table <- readRDS("data/shift_count_table.RDS")

# Left-handed table
shift_count_table %>%
  filter(!game_year %in% c("2020","2022"), stand == "L") %>%
  select(-if_fielding_alignment, -stand) %>%
  kable(col.names = c("Year", "Shifted Plate Appearances (L)"))

# Right-handed table
shift_count_table %>%
  filter(!game_year %in% c("2020","2022"), stand == "R") %>%
  select(-if_fielding_alignment, -stand) %>%
  kable(col.names = c("Year", "Shifted Plate Appearances (L)"))
```


## Basic linear modeling

```{r}
init_linear_model <- lm(woba_value ~ general_pitch_type + 
                          game_year + 
                          if_fielding_alignment + 
                          zone + 
                          stand+ 
                          p_throws+ 
                          woba + 
                          #stand * if_fielding_alignment,
                          p_throws * stand * if_fielding_alignment, 
                          #zone * if_fielding_alignment * general_pitch_type, 
                        data = statcast_at_bat_model_data)


summary(init_linear_model)
```

```{r}
library(ggfortify)
autoplot(init_linear_model)
```

