---
title: "Exploring `baseballr` Package"
author: "Nicholas Esposito & Amber Potter"
date: "7/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load `baseballr` & Other Packages

```{r}
library(baseballr)
library(glue)
library(tidyverse)
```

## Download Batter Data

```{r}
#statcast_data_batters <- statcast_search_batters(start_date = "2022-06-29",
                                                 #end_date = "2022-06-31")

year <- seq(2015, 2022, 1)

for (i in 1:8){
  write.csv(annual_statcast_query(year[i]), 
            file = glue("data-amber/statcast_data_batters", year[i]))
}
```

```{r}
library(baseballr)
library(tidyverse)
library(DBI)
library(RPostgreSQL)

annual_statcast_query <- function(season) {
  
  dates <- seq.Date(as.Date(paste0(season, '-03-01')),
                    as.Date(paste0(season, '-12-01')), by = 'week')
  
  date_grid <- tibble(start_date = dates, 
                      end_date = dates + 6)
  
  safe_savant <- safely(scrape_statcast_savant)
  
  payload <- map(.x = seq_along(date_grid$start_date), 
                 ~{message(paste0('\nScraping week of ', date_grid$start_date[.x], '...\n'))
                   
                   payload <- safe_savant(start_date = date_grid$start_date[.x], 
                                          end_date = date_grid$end_date[.x], type = 'pitcher')
                   
                   return(payload)
                 })
  
  payload_df <- map(payload, 'result')
  
  number_rows <- map_df(.x = seq_along(payload_df), 
                        ~{number_rows <- tibble(week = .x, 
                                                number_rows = length(payload_df[[.x]]$game_date))}) %>%
    filter(number_rows > 0) %>%
    pull(week)
  
  payload_df_reduced <- payload_df[number_rows]
  
  combined <- payload_df_reduced %>%
    bind_rows()
  
  return(combined)
  
}


format_append_statcast <- function(df) {
  
  # function for appending new variables to the data set
  
  additional_info <- function(df) {
    
    # apply additional coding for custom variables
    
    df$hit_type <- with(df, ifelse(type == "X" & events == "single", 1,
                                   ifelse(type == "X" & events == "double", 2,
                                          ifelse(type == "X" & events == "triple", 3, 
                                                 ifelse(type == "X" & events == "home_run", 4, NA)))))
    
    df$hit <- with(df, ifelse(type == "X" & events == "single", 1,
                              ifelse(type == "X" & events == "double", 1,
                                     ifelse(type == "X" & events == "triple", 1, 
                                            ifelse(type == "X" & events == "home_run", 1, NA)))))
    
    df$fielding_team <- with(df, ifelse(inning_topbot == "Bot", away_team, home_team))
    
    df$batting_team <- with(df, ifelse(inning_topbot == "Bot", home_team, away_team))
    
    df <- df %>%
      mutate(barrel = ifelse(launch_angle <= 50 & launch_speed >= 98 & launch_speed * 1.5 - launch_angle >= 117 & launch_speed + launch_angle >= 124, 1, 0))
    
    df <- df %>%
      mutate(spray_angle = round(
        (atan(
          (hc_x-125.42)/(198.27-hc_y)
        )*180/pi*.75)
        ,1)
      )
    
    df <- df %>%
      filter(!is.na(game_year))
    
    return(df)
  }
  
  df <- df %>%
    additional_info()
  
  df$game_date <- as.character(df$game_date)
  
  df <- df %>%
    arrange(game_date)
  
  df <- df %>%
    filter(!is.na(game_date))
  
  df <- df %>%
    ungroup()
  
  df <- df %>%
    select(setdiff(names(.), c("error")))
  
  cols_to_transform <- c("fielder_2", "pitcher_1", "fielder_2_1", "fielder_3",
                         "fielder_4", "fielder_5", "fielder_6", "fielder_7",
                         "fielder_8", "fielder_9")
  
  df <- df %>%
    mutate_at(.vars = cols_to_transform, as.numeric) %>%
    mutate_at(.vars = cols_to_transform, function(x) {
      ifelse(is.na(x), 999999999, x)
    })
  
  data_base_column_types <- read_csv("https://app.box.com/shared/static/q326nuker938n2nduy81au67s2pf9a3j.csv")
  
  character_columns <- data_base_column_types %>%
    filter(class == "character") %>%
    pull(variable)
  
  numeric_columns <- data_base_column_types %>%
    filter(class == "numeric") %>%
    pull(variable)
  
  integer_columns <- data_base_column_types %>%
    filter(class == "integer") %>%
    pull(variable)
  
  df <- df %>%
    mutate_if(names(df) %in% character_columns, as.character) %>%
    mutate_if(names(df) %in% numeric_columns, as.numeric) %>%
    mutate_if(names(df) %in% integer_columns, as.integer)
   
  return(df)
}
```



## Download Pitcher Data

```{r}
statcast_data_pitchers <- statcast_search_pitchers(start_date = "2022-04-01",
                                                   end_date = Sys.Date())

statcast_data_batters %>%
  distinct(description)
```


## Cleaning

```{r}
statcast_data_batters <- statcast_data_batters[ , colSums(is.na(statcast_data_batters)) < nrow(statcast_data_batters)]

statcast_data_pitchers <- statcast_data_pitchers[ , colSums(is.na(statcast_data_pitchers)) < nrow(statcast_data_pitchers)]
```


## EDA

```{r}
# statcast_data_batters %>%
#   drop_na() %>%
#   group_by(if_fielding_alignment) %>%
#   summarize(count = n())

statcast_data_pitchers <- statcast_data_pitchers %>%
  mutate(pitch_outcome = case_when(events != "" ~ events,
                                   events == "" ~ description)) %>%
  mutate(pitch_outcome = case_when(events == "strikeout" & description == "swinging_strike" ~ "strikeout_swinging",
                                   events == "strikeout" & description == "called_strike" ~ "strikeout_called",
                                   TRUE ~ pitch_outcome),
         game_id = game_pk) %>%
  select(-game_pk)
  

statcast_data_batters <- statcast_data_batters %>%
  mutate(pitch_outcome = case_when(events != "" ~ events,
                                   events == "" ~ description)) %>%
  mutate(pitch_outcome = case_when(events == "strikeout" & description == "swinging_strike" ~ "strikeout_swinging",
                                   events == "strikeout" & description == "called_strike" ~ "strikeout_called",
                                   TRUE ~ pitch_outcome),
         game_id = game_pk) %>%
  select(-game_pk)


```

## Creating at bat number column

```{r}
statcast_data_batters_at_bat <- statcast_data_batters %>%
  count(game_id, batter, at_bat_number) %>%
  group_by(game_id, batter) %>%
  mutate(at_bat_of_game=1:n()) %>%
  select(-n)

statcast_data_batters <- statcast_data_batters %>%
  left_join(statcast_data_batters_at_bat, 
            by = c("game_id" = "game_id", 
                   "batter" = "batter", 
                   "at_bat_number" = "at_bat_number")) 


statcast_data_pitchers_at_bat <- statcast_data_pitchers %>%
  count(game_id, batter, at_bat_number) %>%
  group_by(game_id, batter) %>%
  mutate(at_bat_of_game=1:n()) %>%
  select(-n)

statcast_data_pitchers <- statcast_data_pitchers %>%
  left_join(statcast_data_pitchers_at_bat, 
            by = c("game_id" = "game_id", 
                   "batter" = "batter", 
                   "at_bat_number" = "at_bat_number")) 
```



## Counts and Percentages of Sample


```{r}
statcast_data_batters %>%
  filter(!if_fielding_alignment == "", !of_fielding_alignment == "") %>%
  #select(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  count(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  mutate(prob = n/sum(n))
```


```{r}
statcast_data_batters %>%
  filter(!if_fielding_alignment == "", !of_fielding_alignment == "") %>%
  mutate(if_fielding_alignment = case_when(if_fielding_alignment == "Infield shift" ~ "Shift",
                                           if_fielding_alignment == "Strategic" ~ "Shift",
                                           if_fielding_alignment == "Standard" ~ "Standard")) %>%
  mutate(of_fielding_alignment = case_when(of_fielding_alignment == "4th outfielder" ~ "Shift",
                                           of_fielding_alignment == "Strategic" ~ "Shift",
                                           of_fielding_alignment == "Standard" ~ "Standard")) %>%
  #select(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  count(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  mutate(prob = n/sum(n))
```

```{r}
statcast_data_batters %>%
  #select(stand, p_throws, if_fielding_alignment, of_fielding_alignment) %>%
  count(stand, p_throws) %>%
  mutate(prob = n/sum(n))
```